#!/usr/bin/env node
"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const fs_1 = require("fs");
const path_1 = __importDefault(require("path"));
const open_1 = __importDefault(require("open"));
const yargs_1 = __importDefault(require("yargs/yargs"));
const helpers_1 = require("yargs/helpers");
const template_types_1 = __importDefault(require("../plugin/template-types"));
const warn_1 = require("../plugin/warn");
const index_1 = require("../plugin/index");
const version_1 = require("../plugin/version");
const render_template_1 = require("../plugin/render-template");
const argv = (0, yargs_1.default)((0, helpers_1.hideBin)(process.argv))
    .strict()
    .option("filename", {
    describe: "Output file name",
    type: "string",
    default: "./stats.html",
})
    .option("title", {
    describe: "Output file title",
    type: "string",
    default: "EsBuild Visualizer",
})
    .option("template", {
    describe: "Template type",
    type: "string",
    choices: template_types_1.default,
    default: "treemap",
})
    .option("metadata", {
    describe: "Input file name",
    array: true,
    default: ["./metadata.json"],
})
    .option("open", {
    describe: "Open file in browser",
    boolean: true,
    default: false,
})
    .help()
    .parseSync();
const run = async (args) => {
    var _a, _b;
    if (args.metadata.length === 0) {
        throw new Error("Empty file list");
    }
    const fileContents = await Promise.all(args.metadata.map(async (file) => {
        const textContent = await fs_1.promises.readFile(file, { encoding: "utf-8" });
        const jsonContent = JSON.parse(textContent);
        const data = (0, index_1.prepareVisualizerData)(jsonContent);
        return { file, data };
    }));
    const tree = {
        name: "root",
        children: [],
    };
    const nodeParts = {};
    const nodeMetas = {};
    for (const { file, data } of fileContents) {
        if (data.version !== version_1.version) {
            (0, warn_1.warn)(`Version in ${file} is not supported (${data.version}). Current version ${version_1.version}. Skipping...`);
            continue;
        }
        if (data.tree.name === "root") {
            tree.children = tree.children.concat(data.tree.children);
        }
        else {
            tree.children.push(data.tree);
        }
        Object.assign(nodeParts, data.nodeParts);
        Object.assign(nodeMetas, data.nodeMetas);
    }
    const title = (_a = args.title) !== null && _a !== void 0 ? _a : "EsBuild Visualizer";
    const template = (_b = args.template) !== null && _b !== void 0 ? _b : "treemap";
    const data = {
        version: version_1.version,
        tree,
        nodeParts,
        nodeMetas,
        env: {},
        options: { gzip: false, brotli: false, sourcemap: false },
    };
    const fileContent = await (0, render_template_1.renderTemplate)(template, {
        title,
        data,
    });
    await fs_1.promises.mkdir(path_1.default.dirname(args.filename), { recursive: true });
    await fs_1.promises.writeFile(args.filename, fileContent);
    if (args.open) {
        await (0, open_1.default)(args.filename);
    }
};
run(argv).catch((err) => {
    (0, warn_1.warn)(err.stack);
    process.exit(1);
});
