name: Changesets
on:
    push:
        branches:
            - main
env:
    CI: true
    PNPM_CACHE_FOLDER: .pnpm-store
jobs:
    version:
        timeout-minutes: 15
        runs-on: ubuntu-latest
        steps:
            - name: checkout code repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: setup node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20
                  registry-url: https://registry.npmjs.org/
                  scope: "@arizeai"
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            - name: Setup PNPM
              uses: pnpm/action-setup@v4
              with:
                  version: 9.8.0
            - name: setup pnpm config
              run: pnpm config set store-dir $PNPM_CACHE_FOLDER
            - name: install dependencies
              run: pnpm install
            - name: Setup npmrc
              # cp .npmrc to $HOME, append authToken to .npmrc
              # changeset will use the .npmrc in $HOME, and writing there instead of in the repo
              # prevents pnpm from complaining about a dirty worktree
              run: |
                  cp .npmrc $HOME
                  echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> $HOME/.npmrc
            - name: create and publish versions
              uses: changesets/action@v1
              with:
                  version: pnpm ci:version
                  commit: "chore: update versions"
                  title: "chore: update versions"
                  publish: pnpm ci:publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
